const data = [
    {
        id : "1",
        nombre : "Calculadora Snes",
        descripcion: "Calculadora realizada integramente con Javascript.",
        gif : "/imagenes/CalculadoraSnes.gif",
        link : "https://calculadorasnes.vercel.app/" ,
    },
    {
        id : "2",
        nombre : "Pagina montañismo",
        descripcion: "Pagina estatica realizada con HTML y CSS. Parte del desarrollo para el curso de Desarrollo web",
        gif : "/imagenes/ProyectoMontaña.gif",
        link : "https://ferastrozombie.github.io/ProyectoMontania/" ,
    },
    {
        id : "3",
        nombre : "Tienda Pokemon",
        descripcion: "Ecommerce realizado con ReactJs para el curso de Frontend. Simula una tienda pokemon, donde se puede realizar compras de diversos elementos. Sefinaliza la compra con un formuladrio. Los datos se guardan en una base de datos de Firebase. Los productos tambien se traen desde dicha base de datos",
        gif : "/imagenes/TiendaPokemon.gif",
        link : "https://tiendapokemon.vercel.app/" ,
    },
    {
        id : "4",
        nombre : "Tienda Remeras",
        descripcion: "Ecoomerce de remeras. Realizado con HTML, CSS y Javascript. Por medio de javascript se pueden agregar productos a un carrito y visualizarlos en el mismo. Realizado como trabajo final del curso de Javascript, el cual obtubo una nota de 10",
        gif : "/imagenes/RagnarosRemeras.gif",
        link : "https://ferastrozombie.github.io/ragnaros/" ,
    },
    {
        id : "5",
        nombre : "Tienda Guitarras",
        descripcion: "Ecommerce de guitarras realizado con ReactJs, una base de datos de Firebase para obtener los productos y renderizarlos. Se puede simular una compra.",
        gif : "/imagenes/TiendaGuitarras.gif",
        link : "https://tienda-de-guitarras.vercel.app/" ,
    },
    {
        id : "6",
        nombre : "App clima",
        descripcion: "App de clima realizada en ReactJs. Se implementa una api con datos del clima. Se puede introducir cualquier ciudad y nos devuelve los datos actuales del clima",
        gif : "/imagenes/ClimaApp.gif",
        link : "https://climacool.vercel.app/" ,
    },
    {
        id : "8",
        nombre : "Juego ta-te-ti",
        descripcion: "Clasico juego de ta-te-ti o tres en linea. Realizada en ReactJs.",
        gif : "/imagenes/Ta-te-ti.gif",
        link : "https://ta-te-ti-game.vercel.app/" ,
    },
    {
        id : "9",
        nombre : "Perfiles github",
        descripcion: "Buscador de perfiles de Github. Se introduce un nombre o user y nos devuelve el nombre y un link para visitar el perfil. Realizado en ReactJs",
        gif : "/imagenes/github.gif",
        link : "https://ferastrozombie-githubusers.vercel.app/" ,
    },
    {
        id : "10",
        nombre : "Memotest pokemon",
        descripcion: "Juego de memoria Pokemon. Se trara de encontrar las figuras iguales hasta completar el total. Realizado en ReactJs",
        gif : "/imagenes/memotest.gif",
        link : "https://ferastrpzombie-poketest.vercel.app/" ,
    },
    {
        id : "11",
        nombre : "Palabras por minuto",
        descripcion: "Juego de tipeo de palabras aleatorias durante un tiempo de 60 seg. Esta realizado con ReactJs",
        gif : "/imagenes/palabrasporminuto.gif",
        link : "https://ferastrozombie-palabrasxminuto.vercel.app/" ,
    },
    {
        id : "12",
        nombre : "Quien es este pokemon",
        descripcion: "Juego de adivinanza de cual es la silueta del pokemon que se esconde detras del arbusto. Realizada en ReactJs",
        gif : "/imagenes/quienes.gif",
        link : "https://ferastrozombie-palabrasxminuto.vercel.app/" ,
    },
    {
        id : "13",
        nombre : "Buscador peliculas",
        descripcion: "Buscador de peliculas que permite ordenarlas por fecha. Esta realizado en ReactJs",
        gif : "/imagenes/peliculas.gif",
        link : "https://peliculas-nine.vercel.app/" ,
    },
    {
        id : "14",
        nombre : "Pokedex",
        descripcion: "Aplicacion simulando una pokedex realizada en ReactJs. Se implemento la api de Pokemon para traer los datos de los mismos",
        gif : "/imagenes/pokedex.gif",
        link : "https://pokeapi1.vercel.app/" ,
    },
    {
        id : "15",
        nombre : "Lista de tareas",
        descripcion: "Lista de tareas a realizar. Se pueden introducir tareas y marcarlas como realizadas, editarlas y borrarlas. Esta realizada en Javascript y se utiliza localstorage para el almacenamiento local",
        gif : "/imagenes/tareas.gif",
        link : "https://lista-to-do-app.vercel.app/" ,
    },
]

export default data